# sample config with imperfections

host = localhost
port= 8080
 db_name = my_app   
user=admin
password = secret4327

timeout    =    10000
enable_cache= false
path = /opt/newapp

# значение с пробелами
site_name =   test config 

# табы вокруг знака равенства
log_level	=	info

# строка из одних пробелов (будет проигнорирована вашим парсером)

 
# ещё одна пустая строка ниже